### PR TITLE
reCaptcha

### PR DESCRIPTION
**Pull request by zeroninefourfour**

### CODE REVIEW

**Comment by PlanetTheCloud** [comment]
Too many unrelated changes. Please submit a new pull request with a 2.0 base as right now it looks like it still has leftovers from v1.8.
Also do not add Unstable features please

**Comment by zeroninefourfour** [comment]
ok very stable but master branch is 2.0

**Comment by PlanetTheCloud** [comment]
It looks like you're including the system config to $sysConfig, which is NOT recommended. Please use the `config()` function instead. You can do `config('system.captcha.key')` or something like that

**Comment by zeroninefourfour** [comment]
done

**Comment by 4yx** [comment]
Why did you close this? @ImLoadingUuU

**Comment by zeroninefourfour** [comment]
> Why did you close this? @ImLoadingUuU

i found a very weird bug.

the api return data is
```json
{
  "success": true,
  "challenge_ts": "2023-04-30T13:11:21Z",
  "hostname": "localhost"
}{"status":"error","message":"Something went wrong, please try again later.","dev_details":{"exception":"Error","message":"Undefined constant \"success\"","file":"\/opt\/homebrew\/var\/www\/sys-auth\/api\/signup.php","line":35},"DEVELOPMENT_MODE":true}
``` 
theres 2 json, one is Google reCaptcha API,one is VistaPanel Create Account API. idk where is wrong with my code!

**Comment by zeroninefourfour** [comment]
oh wait. after this reply i think i found the problem
`HostingAccount.php` curl variable is same as reCaptcha Verification Part. 
they are $result too! (edit no.

**Pull request closed without merging**
